### ISSUE TITLE
Entanglement in subclasses

### ISSUE THREAD

**Issue by Aurif** [Aurif/Algiz#1]
![image](https://user-images.githubusercontent.com/78136833/160917433-e5a7e636-6144-4889-8195-36f4097bca20.png)

**Comment by Aurif** [comment]
![image](https://user-images.githubusercontent.com/78136833/160918924-5cf361c2-36de-4f9d-9e1f-1356d0b1d4b6.png)

**Comment by VECTR0** [comment]
![obraz](https://user-images.githubusercontent.com/32399848/160920037-42f7454b-f314-4478-8b05-45ec053ca840.png)

**Comment by Aurif** [comment]
![image](https://user-images.githubusercontent.com/78136833/161447692-130754a7-4248-4f66-9c32-5b1ce4f7a992.png)
